# Generated by Django 2.0.1 on 2018-01-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180115_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autho',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titl',
        ),
    ]
